#!/usr/bin/env bash
# Shared helpers for Helply OCI scripts.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OCI_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$OCI_DIR/.." && pwd)"

log()  { echo "[helply-oci] $*" >&2; }
warn() { echo "[helply-oci] WARN: $*" >&2; }
die()  { echo "[helply-oci] ERROR: $*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

load_env() {
  local env_file="${HELPLY_ENV_FILE:-$OCI_DIR/env.local}"
  if [[ ! -f "$env_file" ]]; then
    die "Config not found: $env_file — copy scripts/oci/env.example to scripts/oci/env.local"
  fi
  # shellcheck disable=SC1090
  source "$env_file"
  : "${HELPLY_COMPARTMENT_OCID:?Set HELPLY_COMPARTMENT_OCID in env.local}"
  : "${HELPLY_REGION:?Set HELPLY_REGION in env.local}"
  export OCI_CLI_REGION="$HELPLY_REGION"
}

save_state() {
  local state_file="${HELPLY_STATE_FILE:-$OCI_DIR/.state.env}"
  mkdir -p "$(dirname "$state_file")"
  cat > "$state_file" <<EOF
# Generated by Helply OCI provision — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
HELPLY_VCN_OCID=${HELPLY_VCN_OCID:-}
HELPLY_APP_SUBNET_OCID=${HELPLY_APP_SUBNET_OCID:-}
HELPLY_WORKER_SUBNET_OCID=${HELPLY_WORKER_SUBNET_OCID:-}
HELPLY_APP_SECURITY_LIST_OCID=${HELPLY_APP_SECURITY_LIST_OCID:-}
HELPLY_WORKER_SECURITY_LIST_OCID=${HELPLY_WORKER_SECURITY_LIST_OCID:-}
HELPLY_APP_INSTANCE_OCID=${HELPLY_APP_INSTANCE_OCID:-}
HELPLY_WORKER_INSTANCE_OCID=${HELPLY_WORKER_INSTANCE_OCID:-}
HELPLY_APP_PUBLIC_IP=${HELPLY_APP_PUBLIC_IP:-}
HELPLY_APP_PRIVATE_IP=${HELPLY_APP_PRIVATE_IP:-}
HELPLY_WORKER_PUBLIC_IP=${HELPLY_WORKER_PUBLIC_IP:-}
HELPLY_WORKER_PRIVATE_IP=${HELPLY_WORKER_PRIVATE_IP:-}
HELPLY_VCN_CIDR=${HELPLY_VCN_CIDR:-10.0.0.0/16}
EOF
  log "State saved → $state_file"
}

load_state() {
  local state_file="${HELPLY_STATE_FILE:-$OCI_DIR/.state.env}"
  [[ -f "$state_file" ]] || die "State file missing: $state_file — run provision-all.sh first"
  # shellcheck disable=SC1090
  source "$state_file"
}

oci_find_by_name() {
  # Usage: oci_find_by_name <resource_type> <display_name>
  # resource_type: vcn | subnet | instance | security-list
  local resource_type="$1"
  local name="$2"
  local cid="$HELPLY_COMPARTMENT_OCID"

  case "$resource_type" in
    vcn)
      oci network vcn list --compartment-id "$cid" --display-name "$name" \
        --query 'data[0].id' --raw-output 2>/dev/null | grep -v '^None$' || true
      ;;
    subnet)
      oci network subnet list --compartment-id "$cid" --display-name "$name" \
        --query 'data[0].id' --raw-output 2>/dev/null | grep -v '^None$' || true
      ;;
    instance)
      oci compute instance list --compartment-id "$cid" --display-name "$name" \
        --query 'data[0].id' --raw-output 2>/dev/null | grep -v '^None$' || true
      ;;
    security-list)
      oci network security-list list --compartment-id "$cid" --display-name "$name" \
        --query 'data[0].id' --raw-output 2>/dev/null | grep -v '^None$' || true
      ;;
    *)
      die "Unknown resource type: $resource_type"
      ;;
  esac
}

wait_for_instance_running() {
  local instance_ocid="$1"
  local name="$2"
  log "Waiting for $name to reach RUNNING..."
  local state
  state="$(oci compute instance get --instance-id "$instance_ocid" \
    --query 'data."lifecycle-state"' --raw-output 2>/dev/null || echo "UNKNOWN")"
  if [[ "$state" == "RUNNING" ]]; then
    log "$name is already RUNNING"
    return 0
  fi
  oci compute instance get --instance-id "$instance_ocid" \
    --wait-for-state RUNNING --max-wait-seconds 600 >/dev/null 2>&1 || true
}

get_instance_ips() {
  local instance_ocid="$1"
  local vnic_json
  vnic_json="$(oci compute instance list-vnics --instance-id "$instance_ocid" --all)"
  export _INSTANCE_PUBLIC_IP
  export _INSTANCE_PRIVATE_IP
  _INSTANCE_PUBLIC_IP="$(echo "$vnic_json" | jq -r '.data[0]["public-ip"] // empty')"
  _INSTANCE_PRIVATE_IP="$(echo "$vnic_json" | jq -r '.data[0]["private-ip"] // empty')"
}

read_ssh_public_key() {
  local key_file="${HELPLY_SSH_PUBLIC_KEY_FILE/#\~/$HOME}"
  [[ -f "$key_file" ]] || die "SSH public key not found: $key_file"
  cat "$key_file"
}

resolve_ubuntu_image_ocid() {
  if [[ -n "${HELPLY_UBUNTU_IMAGE_OCID:-}" ]]; then
    echo "$HELPLY_UBUNTU_IMAGE_OCID"
    return
  fi

  local shape="${HELPLY_INSTANCE_SHAPE:-VM.Standard.E2.1.Micro}"
  log "Resolving Ubuntu 24.04 image for shape $shape..."

  oci compute image list \
    --compartment-id "$HELPLY_COMPARTMENT_OCID" \
    --operating-system "Canonical Ubuntu" \
    --operating-system-version "24.04" \
    --shape "$shape" \
    --sort-by TIMECREATED \
    --sort-order DESC \
    --query 'data[0].id' \
    --raw-output
}

build_shape_args() {
  local shape="${HELPLY_INSTANCE_SHAPE:-VM.Standard.E2.1.Micro}"
  if [[ "$shape" == "VM.Standard.A1.Flex" ]]; then
    local ocpus="${HELPLY_A1_OCPUS:-1}"
    local mem="${HELPLY_A1_MEMORY_GB:-6}"
    echo "--shape $shape --shape-config {\"ocpus\":$ocpus,\"memoryInGBs\":$mem}"
  else
    echo "--shape $shape"
  fi
}

check_prerequisites() {
  require_cmd oci
  require_cmd jq
  oci iam region list --query 'data[?"name"==`'"$HELPLY_REGION"'`]' --raw-output \
    | grep -q . || die "OCI CLI not configured for region $HELPLY_REGION — run: oci setup config"
  log "OCI CLI OK (region=$HELPLY_REGION)"
}
